---
title: "GVPT628 Final Project Data Pull and Cleaning"
author: "Zach Einolf"
date: "2025-12-16"
output: pdf_document
---

```{r, include=FALSE}
library(readr)
library(dplyr)
library(tidyverse)
library(cluster)
library(factoextra)
library(ggplot2)
library(haven)
library(doBy)
library(tidyr)
library(acled.api)
library(httr)
library(httr2)
library(purrr)
library(xml2)
library(httr)
library(httr2)
library(readr)
library(stringr)
library(DBI)
library(RSQLite)
library(scales)
library(fastDummies)
```

Reading in open-source data from Asian Barometer in Waves
```{r}
w3<-read_dta("../data/W3/W3_6_Philippines_Renew20240328.dta")
w4<-read_dta("../data/W4/W4_Philippines_20240308_release.dta")
w5<-read_dta("../data/W5/ABS Wave 5 Philippines_Core_merged_20201223_release.dta")
w6<-read_dta("../data/W6/W6_Philippines_release_20240403.dta")
```

AB Wave 3 Cleaning
```{r, warning =FALSE}
#subselecting
sw3 <- w3|>
  select(idnumber, region, ir13, se5, se3a, se2, q120, q156, q157a, q158, q159, q160, q161)

#renaming
ab_wave3_c <- sw3|>
  mutate(
    wave = 3,
    idnumber = idnumber,
    year = 2010,
    region = region,
    locality_level = ir13,
    education = se5,
    age = se3a,
    gender = se2,
    asia_influence = q156,
    china_harm = q157a,
    asia_future_inf = q158,
    model_development = q159,
    china_deg_inf = q160,
    china_inf_op = q161,
    china_dem = q120)|>
select(wave,
       idnumber,
       year,
       region,
       locality_level,
       education,
       age,
       gender,
       asia_influence,
       china_harm,
       asia_future_inf,
       model_development,
       china_deg_inf,
       china_inf_op,
       china_dem)

#writing to db
con <- dbConnect(SQLite(), "../data/ab_wave3_c.db")
dbWriteTable(con, "ab_wave3_c.db", ab_wave3_c, overwrite = TRUE)
dbDisconnect(con)

```


AB Wave 4 Cleaning
```{r, warning =FALSE}
#subselecting
sw4 <- w4|>
  select(idnumber, year, region, ir13, se5, se3_2, se2, q99, q121, q153, q163, q165, q166, q167, q168, q169)

#renaming
ab_wave4_c <- sw4|>
  mutate(
    wave = 4,
    idnumber = idnumber,
    year = year,
    region = case_when(
      region %in% 601 ~ 1,
      region %in% 602 ~ 2,
      region %in% 603 ~ 3,
      region %in% 604 ~ 4,
      TRUE ~ NA_real_
),
    locality_level = ir13,
    education = se5,
    age = se3_2,
    gender = se2,
    asia_influence = q163,
    china_harm = q165,
    asia_future_inf = q166,
    model_development = q167,
    china_deg_inf = q168,
    china_inf_op = q169,
    china_dem = q121,
    foreign_immigration = q153,
    country_problem1 = q99)|>
select(wave,
       idnumber,
       year,
       region,
       locality_level,
       education,
       age,
       gender,
       asia_influence,
       china_harm,
       asia_future_inf,
       model_development,
       china_deg_inf,
       china_inf_op,
       china_dem,
       foreign_immigration,
       country_problem1)

#writing to db
con <- dbConnect(SQLite(), "../data/ab_wave4_c.db")
dbWriteTable(con, "ab_wave4_c.db", ab_wave4_c, overwrite = TRUE)
dbDisconnect(con)

```


AB Wave 5 Cleaning
```{r, warning =FALSE}
#subselecting
sw5 <- w5|>
  select(IDnumber, Year, Region, IR13, Se5, Se3_1, Se2, Q174, Q177, Q178, Q179, Q180, Q181, Q182, Q128, Q185, Q156, Q156a, Q158, Q106)

#renaming
ab_wave5_c <- sw5|>
  mutate(
    wave = 5,
    idnumber = IDnumber,
    year = Year,
    region = Region,
    locality_level = IR13,
    education = Se5,
    age = Se3_1,
    gender = Se2,
    asia_influence = Q174,
    china_harm = Q177,
    asia_future_inf = Q179,
    model_development = Q180,
    china_deg_inf = Q181,
    china_inf_op = Q182,
    china_world_inf = case_when(
      Q178 %in% 1:2 ~ 6,
      Q178 %in% 3:4 ~ 5,
      Q178 == 5 ~ 4,
      Q178 == 6 ~ 3,
      Q178 %in% 7:8 ~ 2,
      Q178 %in% 9:10 ~ 1,
      Q178 == 97 ~ 7,
      Q178 == 98 ~ 8,
      Q178 == 99 ~ 9,
      TRUE ~ NA_real_
),
  china_dem = Q128,
  aspect_power = Q185,
  way_of_life = Q156,
  foreign_immigration = Q158,
  country_problem1 = Q106)|>
select(wave,
       idnumber,
       year,
       region,
       locality_level,
       education,
       age,
       gender,
       asia_influence,
       china_harm,
       china_world_inf,
       asia_future_inf,
       model_development,
       china_deg_inf,
       china_inf_op,
       china_world_inf,
       china_dem,
       aspect_power,
       way_of_life,
       foreign_immigration,
       country_problem1)

#writing to db
con <- dbConnect(SQLite(), "../data/ab_wave5_c.db")
dbWriteTable(con, "ab_wave5_c.db", ab_wave5_c, overwrite = TRUE)
dbDisconnect(con)

```


AB Wave 6 Cleaning
```{r}
#subselecting
sw6 <- w6|>
  select(idnumber, year, region, IR13, SE5, SE3_1, SE2, Q173, Q176, Q177, Q179, Q180, Q181, Q182, Q120, Q185, Q156, Q158, Q97)

#renaming
ab_wave6_c <- sw6|>
  mutate(
    wave = 6,
    idnumber = idnumber,
    year = year,
    region = case_when(
      region %in% 601 ~ 1,
      region %in% 602 ~ 2,
      region %in% 603 ~ 3,
      region %in% 604 ~ 4,
      TRUE ~ NA_real_
),
    locality_level = IR13,
    education = SE5,
    age = SE3_1,
    gender = SE2,
    asia_influence = Q173,
    china_harm = Q176,
    china_world_inf = Q177,
    asia_future_inf = Q179,
    model_development = Q180,
    china_deg_inf = Q181,
    china_inf_op = Q182,
    china_world_inf = Q177,
  china_dem = Q120,
  aspect_power = Q185,
  way_of_life = Q156,
  foreign_immigration = Q158,
  country_problem1 = Q97)|>
select(wave,
       idnumber,
       year,
       region,
       locality_level,
       education,
       age,
       gender,
       asia_influence,
       china_harm,
       china_world_inf,
       asia_future_inf,
       model_development,
       china_deg_inf,
       china_inf_op,
       china_world_inf,
       china_dem,
       aspect_power,
       way_of_life,
       foreign_immigration,
       country_problem1)

#writing to db
con <- dbConnect(SQLite(), "../data/ab_wave6_c.db")
dbWriteTable(con, "ab_wave6_c.db", ab_wave6_c, overwrite = TRUE)
dbDisconnect(con)
```


Combining Waves
```{r}
#binding rows together
comb_data <- bind_rows(ab_wave3_c, ab_wave4_c, ab_wave5_c, ab_wave6_c) |>
arrange(year, wave, idnumber)

#Turning non-responses into NA
comb_data <- comb_data |>
  mutate(
    across(
      c(
        asia_influence, china_harm, china_world_inf, china_deg_inf, china_inf_op, aspect_power, way_of_life, foreign_immigration, asia_future_inf
        ),
      ~ ifelse(.x %in% c(7, 8, 9), NA, .x)))

#Turning non-responses into NA
asia_final <- comb_data |>
  mutate(
    across(
      c(asia_influence, model_development, china_dem, asia_future_inf),
      ~ ifelse(.x %in% c(16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 97, 98, 99), NA, .x)))

#Turning non-responses into NA
asia_final <- asia_final |>
  mutate(
    across(model_development,
           ~ ifelse(.x %in% c(8, 97, 98, 99), NA, .x)))|>
  mutate(
    across(country_problem1,
           ~ ifelse(.x %in% c(990, 997, 998, 998), NA, .x)))

#writing final data to db
con <- dbConnect(SQLite(), "../data/asia_final.db")
dbWriteTable(con, "asia_final.db", asia_final, overwrite = TRUE)
dbDisconnect(con)

```


ACLED API Pull for PHIL
```{r, cache=TRUE}
base_url <- "https://acleddata.com/api/acled/read" #base url 
token <- read_file("access_token.txt") #use your personal access token if you want to recreate

#acled.api function 
resp <- GET(url = base_url,
            query = list(`_format` = "csv",
                         country = "Philippines", #Philippines data
                         event_date = "2010-03-10|2021-10-11", #same time period as AB
                         event_date_where = "BETWEEN",
                         limit = 0),
            add_headers(Authorization = paste("Bearer", token))
            )

#status check
stop_for_status(resp)

#running api pull
csv_txt <- content(resp, as = "text", encoding = "UTF-8")

#reading in as csv
ph_acled <- read_csv(csv_txt, show_col_types = FALSE)
head(ph_acled)
```


ACLED API Pull for CHINA
```{r, cache=TRUE}
base_url <- "https://acleddata.com/api/acled/read" #base url 
token <- read_file("access_token.txt") #use your personal access token if you want to recreate

#acled.api function 
resp <- GET(url = base_url,
            query = list(`_format` = "csv",
                         country = "China", #China
                         event_date = "2010-03-10|2021-10-11", #same time period as AB
                         event_date_where = "BETWEEN",
                         limit = 0),
            add_headers(Authorization = paste("Bearer", token))
            )


#status check
stop_for_status(resp)


#running api pull
csv_txt <- content(resp, as = "text", encoding = "UTF-8")
#reading in as csv
ch_acled <- read_csv(csv_txt, show_col_types = FALSE)

head(ch_acled)
```

ACLED Cleaning

```{r}
#cleaning the philippines data and filtering down for events that only mention china or chinese actors
ph_china_events <- ph_acled|>
  mutate(
    year = year,
    notes = tolower(notes),
    actor1 = tolower(actor1),
    actor2 = tolower(actor2),
    assoc1 = tolower(assoc_actor_1),
    assoc2 = tolower(assoc_actor_2),
    location = tolower(location),
    disorder_type = tolower(disorder_type),
    event_type = tolower(event_type),
    sub_event_type = tolower(sub_event_type),
    china_tf =
      str_detect(notes, "(?i)china|chinese|south china sea | islands") |
      str_detect(actor1, "china|chinese") |
      str_detect(actor2, "china|chinese") |
      str_detect(assoc1, "china|chinese") |
      str_detect(assoc2, "china|chinese")) |>
  filter(china_tf == TRUE) |>
  mutate(
    month = floor_date(event_date, "month"),
    month = as.character(month),
    event_date = as.character(event_date)
)


#cleaning the china data and filtering down for strategic developments that only the philippines or south china sea activity
ch_phil_events <- ch_acled|>
  mutate(
    year = year,
    notes = tolower(notes),
    actor1 = tolower(actor1),
    actor2 = tolower(actor2),
    assoc1 = tolower(assoc_actor_1),
    assoc2 = tolower(assoc_actor_2),
    location = tolower(location),
    disorder_type = tolower(disorder_type),
    event_type = tolower(event_type),
    sub_event_type = tolower(sub_event_type),
    china_tf =
      str_detect(notes, "(?i)philippines|filipino|south china sea| islands") |
      str_detect(actor1, "philippines|filipino") |
      str_detect(actor2, "philippines|filipino") |
      str_detect(assoc1, "philippines|filipino") |
      str_detect(assoc2, "philippines|filipino")) |>
  filter(disorder_type == 'strategic developments', china_tf == TRUE) |>
  mutate(
    month = floor_date(event_date, "month"),
    month = as.character(month),
    event_date = as.character(event_date)
)

#binding both of those dataframes together and subselecting
acled_data <- ph_china_events |>
  bind_rows(ch_phil_events)|>
  select(year,
         event_date,
         month,
         location,
         actor1,
         assoc1,
         actor2,
         assoc2,
         disorder_type,
         event_type,
         sub_event_type,
         fatalities,
         notes)

head(acled_data)

#writing final combined acled data to db
con <- dbConnect(SQLite(), "../data/acled_data.db")
dbWriteTable(con, "acled_data.db", acled_data, overwrite = TRUE)
dbDisconnect(con)
```
